### ISSUE TITLE
Any plans for Proton GE and Proton TKG?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#10]
Are there any plans to add builds for Proton GE and Proton TKG?

Proton GE and Proton TKG are forks of Proton with extra patches to make games run better.

- [Proton GE](https://github.com/GloriousEggroll/proton-ge-custom/)
- [Proton TKG](https://github.com/Frogging-Family/wine-tkg-git/releases/tag/5.21.r0.ge2d9f97b)

**Comment by gasinvein** [comment]
No, I personally don't have plans to flatpak Proton forks, see https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton/issues/4#issuecomment-717564005
