### ISSUE TITLE
Voice sound stopped working in Skyrim in 5.13-2 version

### ISSUE THREAD

**Issue by tim77** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#20]
On previous proton-flatpak build it works, but probably regression in `5.13-2` build.

**How to reproduce:**

Run Skyrim SE with:
```
WINEDLLOVERRIDES="xaudio2_7=n,b" %command%
```

**Actual result:**

No voice sound in game.

**Comment by gasinvein** [comment]
Yep, that's a regression in 5.13, likely caused by the `proton` script setting `GST_PLUGIN_SYSTEM_PATH_1_0` to bundled path and, thus, leaving system gstreamer without plugins.
