### ISSUE TITLE
Replace VKD3D with compiled master version

### ISSUE THREAD

**Issue by TheGreatestJannet** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#23]
Hello I'm looking to replace VKD3D with the latest master I have compiled. Is this possible? I have looked in `~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d` but can't find the proton files. Are they stored somewhere else or is it not possible to modify them.

**Comment by gasinvein** [comment]
Flatpak apps and runtimes are generally stored in `/var/lib/flatpak` or `~/.local/share/flatpak`, but you're not supposed to modify files there. It can break things and will be overwritten on update.
If you want to use updated vkd3d dlls - put them in the wine prefix instead.

**Comment by TheGreatestJannet** [comment]
Thank you is there any instructions on how to add them to the prefix? The readme on the VKD3D doesn't seem to tell you what to do without after compiling it.

**Comment by gasinvein** [comment]
Wine prefixes in Proton are created per-game, so the vkd3d dll should be at
`steamapps/compatdata/STEAM_ID/pfx/drive_c/windows/system32/d3d12.dll`
(path relative to your Steam library, default is `~/.var/app/com.valvesoftware.Steam/data/Steam`)

**Comment by TheGreatestJannet** [comment]
Thank you. Is there a way to check that it is using the one in system32 and not the one that shipped with proton?

**Comment by gasinvein** [comment]
vkd3d in Proton is built as a native (windows) dll, so I believe it's always loaded from the prefix or other windows-space path.

**Comment by TheGreatestJannet** [comment]
Thanks a lot for your help!

**Comment by TheGreatestJannet** [comment]
One last question when I update proton will it replace it?

**Comment by gasinvein** [comment]
Ah. Yes. Proton probably replaces it at every launch. Didn't think about it.
Then I guess the only option is to put the dll in the game directory, near its executable.
