### ISSUE TITLE
GE proton flatpak on flathub?

### ISSUE THREAD

**Issue by romulasry** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#30]
https://github.com/gasinvein/proton-flatpak Think we could have this here? It would be nice to have  GE build without the hassle.

**Comment by romulasry** [comment]
Looks like there already is one: flatpak install com.valvesoftware.Steam.CompatibilityTool.Proton-GE wish I could find it

**Comment by gasinvein** [comment]
Yep, it's already there.
