### ISSUE TITLE
Proton only utilizes integrated graphics

### ISSUE THREAD

**Issue by jonathanfaust** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#35]
Running games with an older Proton version (4.2-9) uses dedicated graphics as expected. But running the same game with this Proton build seems to only use integrated graphics, regardless of setting DRI_PRIME in launch options.

**Comment by gasinvein** [comment]
AFAIK Proton by itself has no control over GPU selection. What GPUs combination do you have? Is DVXK in use for both (or neither) Proton versions? Does something change if you set the enwironment app-wide (`flatpak run --evn=DRI_PRIME=1 com.valvesoftware.Steam`)?

**Comment by jonathanfaust** [comment]
I gave in and downloaded the standard Steam installation alongside the Flatpak. It seems the issue I described occurs there as well. Sorry for prematurely opening an issue and thank you for the response!
