### ISSUE TITLE
Support different versions of Proton

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#4]
I really like the concept of building Proton directly on top of the Free Desktop runtime, so let me quickly praise your work!

That out of the way, I do think that it's neccessary to support different versions of Proton side-by-side. If you check ProtonDB, you can see sometimes fastly different results based on different versions of Proton. Add Glorious Eggrol versions in the mix, and it will be essential to support different versions.

My proposal would be on par with the `org.kde.KStyle.Adwaita` packages. These all have different branches to accommodate all different versions of KDE:

https://github.com/flathub/org.kde.KStyle.Adwaita

**Comment by gasinvein** [comment]
While it's easy to branch out and freeze current Proton version once a new one is released, I don't know how the specific branch can be selected by the user. AFAIK there is no way to tell Flatpak to "run Steam and enable _this_ branch of Proton extension".

**Comment by gasinvein** [comment]
BTW, if you want Proton-GE extension - consider forking this repo, adapting it to GE flavor and submitting it as another extension to Flathub (i.e. `.CompatibilityTool.Proton-GE`). There is clearly some interest in doing this, CC @Saroufim

**Comment by Saroufim** [comment]
Ideally, @GloriousEggroll would be involved in the process or, at the very least, his permission would be granted. It's always a good step to contact upstream first.

**Comment by gasinvein** [comment]
@Eonfge Do you have any examples of games known to work with Proton 5.0 and earlier, but not with 5.13?

**Comment by Eonfge** [comment]
I haven't actually tested that many applications. I'll keep my eyes open, but I don't actually have that many games who are not netive.

**Comment by Saroufim** [comment]
I can help with that part. Almost all my games are non-native. I've already tried manually installing proton-ge with flatpak steam and it works swimmingly well for pre-5.13 proton

**Comment by gasinvein** [comment]
Proton-GE flatpak build is mostly done here flathub/flathub#1953. Anyone willing to test it is welcome to report there how it works for you.
Keep in mind that it's a work-in-progress unofficial build of an unofficial fork, so use at your own risk. Backup the wine prefixes of the games you're planning to run before using it, just in case.

**Comment by TheGreatestJannet** [comment]
Is there any plans for Proton Experimental? It seems Valve is pushing regularly updates to that branch now.

**Comment by gasinvein** [comment]
I'd like to provide proton experimental builds, but not sure how it should be handled. Flatpak doesn't provide an option to select extension branch manually. So we have these options:
- Submit Proton experimental as a separate extension (this is a fail-safe option, but adds some maintenance burden)
- Build experimental Proton on `beta` branch (but this will leave us no place to push untested updates for normal Proton)
- Build experimental Proton on `experimental` branch or something like this (but it'll replace normal Proton once installed)

**Comment by TheGreatestJannet** [comment]
Can't both be installed with com.valvesoftware.Steam.CompatibilityTool.Proton? This has the draw back of using more hard drive space and some users might not want the experimental branch.

**Comment by gasinvein** [comment]
Multiple branches of the same extension ID of `com.valvesoftware.Steam.CompatibilityTool.Proton` can be installed simultaneously (e.g. `stable` and `beta` currently), but the user can't select which one to use. Flatpak will enable only one branch of this extension when Steam is launched.

**Comment by TheGreatestJannet** [comment]
What I meant was that `flatpak install com.valvesoftware.Steam.CompatibilityTool.Proton` could install both Proton and Proton Experimental.

**Comment by gasinvein** [comment]
Any how it could be achieved? By building two protons in the same bundle? Even if it was possible with current layout (it isn't), I don't see any advantages in doing so over building experimental proton as a separate extension.

**Comment by TheGreatestJannet** [comment]
wouldn't they appear as two different options in steam that the user would switch between as they please?

**Comment by gasinvein** [comment]
They would if we build them as distinct compatibility tools.

**Comment by TheGreatestJannet** [comment]
Ah I see. Hopefully there is a way as that means flatpak users could get all the new benefits.

**Comment by gasinvein** [comment]
I've submitted Proton experimental as a separate extension here flathub/flathub#2011

**Comment by TheGreatestJannet** [comment]
Thank you!! Hopefully Red Dead Redemption 2 works on this version!

**Comment by gasinvein** [comment]
@TheGreatestJannet Nah, that's unlikely if my latest guess is right and the problem is related to seccomp/DRM. But you're welcome to test it anyway.

**Comment by TheGreatestJannet** [comment]
I’ll test it and let you know! Can it be fixed as it works with the official proton?

**Comment by gasinvein** [comment]
@TheGreatestJannet Probably, but we need to know exactly what's causes the problem. Also I'm not very familiar with C and seccomp, and there is special [codepath](https://github.com/ValveSoftware/wine/blob/proton_5.13/dlls/ntdll/unix/signal_x86_64.c#L2173) for RDR2 (GE and staging don't have it) that I can't even test due to not having the game. Our seccomp fix seems to work fine for other games (on the codepath for other games), so we probably need to test exactly RDR2.

**Comment by TheGreatestJannet** [comment]
I see. If I can help or if you have a specific build that you think might fix the issue I’d be glad to test it for you.

**Comment by Eonfge** [comment]
Think we can savely close this issue. GE and Proton Exp are now also included

**Comment by gasinvein** [comment]
Since 6.3 is out, if anyone wants to keep 5.13 available on Flathub, I suggest forking this repo, resetting it to the latest commit with 5.13 (probably 9ca868e49bbf81d8d106f782286365ece96e12c5), and submitting it to Flathub under a different ID, e.g. `com.valvesoftware.Steam.CompatibilityTool.Proton-5-13`
