### ISSUE TITLE
New Proton Version 5.13-6

### ISSUE THREAD

**Issue by Bohne13** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#40]
There is a newer version from Proton available

**Comment by gasinvein** [comment]
It's currently available from the `beta` repository.

**Comment by Bohne13** [comment]
ooh yes, I have seen this after filling the issue formular!

**Comment by nickavem** [comment]
Beta branch merge failed: https://flathub.org/builds/#/builders/27/builds/38703

**Comment by gasinvein** [comment]
There is some sort of networking error preventing sources download. Let's hope it'll will disappear on its own soon. Maybe @barthalion know more what's exactly wrong.

**Comment by gasinvein** [comment]
Well, the network error doesn't go away:
```
flatpak-builder: Downloading FAudio
Fetching full git repo https://github.com/ValveSoftware/Proton.git
Fetching full git repo https://github.com/ValveSoftware/wine
Fetching full git repo https://github.com/ValveSoftware/dxvk
remote: Enumerating objects: 9, done.        
remote: Counting objects:  11% (1/9)        
remote: Counting objects:  22% (2/9)        
remote: Counting objects:  33% (3/9)        
remote: Counting objects:  44% (4/9)        
remote: Counting objects:  55% (5/9)        
remote: Counting objects:  66% (6/9)        
remote: Counting objects:  77% (7/9)        
remote: Counting objects:  88% (8/9)        
remote: Counting objects: 100% (9/9)        
remote: Counting objects: 100% (9/9), done.        
remote: Compressing objects: 100% (1/1)        
remote: Compressing objects: 100% (1/1), done.        
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0        
Unpacking objects:  20% (1/5)
Unpacking objects:  40% (2/5)
Unpacking objects:  60% (3/5)
Unpacking objects:  80% (4/5)
Unpacking objects: 100% (5/5)
Unpacking objects: 100% (5/5), 852 bytes | 19.00 KiB/s, done.
From https://github.com/ValveSoftware/dxvk
 * [new ref]           refs/pull/12/head -> refs/pull/12/head
Fetching full git repo https://github.com/ValveSoftware/openvr
Fetching full git repo https://github.com/liberationfonts/liberation-fonts
Fetching full git repo https://github.com/FNA-XNA/FAudio
fatal: unable to access 'https://gitlab.freedesktop.org/gstreamer/gstreamer.git/': Failed sending HTTP2 data
Failed to download sources: module FAudio: Child process exited with code 128
```

**Comment by nickavem** [comment]
I am unable to reproduce this locally running the same command as the bot

**Comment by felipe19930** [comment]
I might be talking nonsense, but wouldn't it be possible to download all git modules as tarballs (I think there are 6 in total?), then extract them into Proton's main repository? At least until this issue gets sorted out...

**Comment by gasinvein** [comment]
It is possible, but this would be a lot of work for just a workaround.

**Comment by felipe19930** [comment]
Yeah, you're right... I'm just too impatient 😄 

And building locally is not an option for me, so I can only wait...

Thanks!

**Comment by gasinvein** [comment]
Well, 5.13-6 was built in `beta`, so you can install it from the 
flathub-beta repository (you'll also need to install Steam beta branch 
from there). Proton beta branch is exactly the same as that was 
supposed to land in `stable`, just keep in mind that, well, it's beta, 
untested updates may land there.

**Comment by felipe19930** [comment]
Nah, it's ok... I'll probably break something if I try to do that, so it's better to just wait for my own sake. Thanks though!

**Comment by gasinvein** [comment]
@nanonyme Maybe we could allow `beta` branches of compatibility tools extensions for Steam `stable` branch?

**Comment by gasinvein** [comment]
Submitted [a build](https://flathub.org/builds/#/builders/32/builds/39745) that should finish successfully and land in the stable repo soon. Thanks @barthalion for workarounding the network issue.
