### ISSUE TITLE
Wine issues: `mismatched architecture` and `unhandled page fault`

### ISSUE THREAD

**Issue by KnightOfCups** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton#64]
Since I'm on Steam, I play the early Tomb Raider games by Core Design (from I to VI) and, despite some temporary issues, I managed to get this working by using the different community versions available of Proton (from here, `-Exp` or `-GE`). Now it seems that few Wine installations have been altered but I still can play the other games.

- For TB II & V, registry files are invalid ([tb2.log](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton/files/7747351/tb2.log) [tb5.log](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton/files/7747353/tb5.log))
  ```
  ...
  system.reg is not a valid registry file
  userdef.reg:4: Mismatched architecture '#arch=win64'
  userdef.reg is not a valid registry file
  user.reg is not a valid registry file
  ...
  ```
  Protontricks crashes after complaining about the WINEPREFIX: `You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.`

- For TB III, wine crashes ([tb3.log](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton/files/7747367/tb3.log))
  ```
  ...
  wine: Unhandled page fault on read access to 6D452064 at address 6D452064 (thread 0118), starting debugger...
  ...
  Unhandled exception: page fault on read access to 0x6d452064 in 32-bit code (0x6d452064).
  ...
  ```
I tried resetting Steam with `--reset` option and uninstalling/reinstalling the Proton builds but the Wine issues remain.

**Comment by KnightOfCups** [comment]
Finally I succeed to launch TB III with current Proton-GE `6.21-GE-2-1` version but not with the latest Proton-Exp ` 6.3-20211220` version (same issue).
The switch to the previous Proton builds for the 2 unworkable games just confirm the diagnostic with a clear message:
`wine: '.../.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/225300/pfx' is a 32-bit installation, it cannot support 64-bit applications.`

**Comment by KnightOfCups** [comment]
Finally I ended up by uninstalling and reinstalling the 2 games, the Wine configurations are now valid and everything is back to normal.

**Comment by gasinvein** [comment]
So I guess the prefixes got broken (IIRC Steam wipes the prefix when uninstalling a game). Now I wonder how exactly they got broken.
